### ISSUE TITLE
Ordem crescente e decrescente 

### ISSUE THREAD

**Issue by michelmir** [danielsmota/AjaxCrudPHP#1]
Olá. Consegue-se inserir dados porém ao ordenar crescente e decrescente no header da tabela, não é ordenado corretamente. Vi que no aruivo fetch.php contém as seguintes linhas (6-19):

`$query .= "SELECT * FROM users ";
if(isset($_POST["search"]["value"]))
{
	$query .= 'WHERE first_name LIKE "%'.$_POST["search"]["value"].'%" ';
	$query .= 'OR last_name LIKE "%'.$_POST["search"]["value"].'%" ';
}
if(isset($_POST["order"]))
{
	$query .= 'ORDER BY '.$_POST['order']['0']['column'].' '.$_POST['order']['0']['dir'].' ';
}
else
{
	$query .= 'ORDER BY id DESC ';
}`

Talvez é nessa parte do código que possivelmente deve ser mexida.

**Comment by danielsmota** [comment]
Olá Michel, atualizei os CDN's e fiz um teste que funcionou corretamente.
Obrigado pelo feedback!
;)

**Comment by danielsmota** [comment]
Não se esqueça de criar uma pasta upload para guardar as fotos.
